#!/bin/bash

# Installs base gems used often

gems=(
  'backup'     \
  'rails'      \
  'rspec'      \
  'pry'        \
  'pry-byebug' \
  'pry-doc'    \
  'pry-rails'  \
  'pry-remote' \
  'sinatra'    \
  'gollum'     \
  'brakeman' \
  'bundler-audit'
)

for gem in "${gems[@]}"; do
  echo "*** Installing gem: ${gem}"
  gem install "${gem}"
done
